openapi: 3.1.0
info:
  title: Shopify Admin REST About Required API
  description: The Shopify Admin REST API lets you build apps and integrations that extend and enhance the Shopify admin. Access products, customers, orders, inventory, fulfillment, and more. Endpoints are organized by resource type and versioned by release date.
  version: 2025-01
  contact:
    name: Shopify
    url: https://shopify.dev/docs/api/admin-rest
    email: api@shopify.com
  license:
    name: Shopify API Terms
    url: https://www.shopify.com/legal/api-terms
  x-date: '2026-03-04'
servers:
- url: https://{store}.myshopify.com/admin/api/2025-01
  description: Shopify Admin REST API
  variables:
    store:
      default: my-store
      description: The Shopify store subdomain
security:
- AccessToken: []
tags:
- name: Required
paths:
  /admin/api/2020-01/application_charges/{application_charge_id}/activate.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  application_charge:
                    id: 675931192
                    name: iPod Cleaning
                    api_client_id: 755357713
                    price: '5.00'
                    status: accepted
                    return_url: http://google.com
                    test: null
                    created_at: '2020-12-07T15:53:44-05:00'
                    updated_at: '2020-12-07T15:53:44-05:00'
                    charge_type: null
                    decorated_return_url: http://google.com?charge_id=675931192
                summary: Activate an application charge
      summary: Shopify This Endpoint Is No Longer Required And Is Deprecated As Of  Api Version 2021-01
      description: https://shopify.dev/docs/admin-api/rest/reference/billing/applicationcharge#activate-2020-01
      parameters:
      - in: path
        name: application_charge_id
        required: true
        schema:
          type: string
        description: application_charge_id
      tags:
      - Required
      responses:
        '200':
          description: ''
      operationId: deprecated_202001_create_application_charges_param_application_charge_id_activate
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-04/application_charges/{application_charge_id}/activate.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  application_charge:
                    id: 675931192
                    name: iPod Cleaning
                    api_client_id: 755357713
                    price: '5.00'
                    status: accepted
                    return_url: http://google.com
                    test: null
                    created_at: '2020-12-07T15:53:44-05:00'
                    updated_at: '2020-12-07T15:53:44-05:00'
                    charge_type: null
                    decorated_return_url: http://google.com?charge_id=675931192
                summary: Activate an application charge
      summary: Shopify This Endpoint Is No Longer Required And Is Deprecated As Of  Api Version 2021-01
      description: https://shopify.dev/docs/admin-api/rest/reference/billing/applicationcharge#activate-2020-04
      parameters:
      - in: path
        name: application_charge_id
        required: true
        schema:
          type: string
        description: application_charge_id
      tags:
      - Required
      responses:
        '200':
          description: ''
      operationId: deprecated_202004_create_application_charges_param_application_charge_id_activate
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-07/application_charges/{application_charge_id}/activate.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  application_charge:
                    id: 675931192
                    name: iPod Cleaning
                    api_client_id: 755357713
                    price: '5.00'
                    status: accepted
                    return_url: http://google.com
                    test: null
                    created_at: '2020-12-07T15:53:44-05:00'
                    updated_at: '2020-12-07T15:53:44-05:00'
                    charge_type: null
                    decorated_return_url: http://google.com?charge_id=675931192
                summary: Activate an application charge
      summary: Shopify This Endpoint Is No Longer Required And Is Deprecated As Of  Api Version 2021-01
      description: https://shopify.dev/docs/admin-api/rest/reference/billing/applicationcharge#activate-2020-07
      parameters:
      - in: path
        name: application_charge_id
        required: true
        schema:
          type: string
        description: application_charge_id
      tags:
      - Required
      responses:
        '200':
          description: ''
      operationId: deprecated_202007_create_application_charges_param_application_charge_id_activate
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-10/application_charges/{application_charge_id}/activate.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  application_charge:
                    id: 675931192
                    name: iPod Cleaning
                    api_client_id: 755357713
                    price: '5.00'
                    status: accepted
                    return_url: http://google.com
                    test: null
                    created_at: '2020-12-07T15:53:44-05:00'
                    updated_at: '2020-12-07T15:53:44-05:00'
                    charge_type: null
                    decorated_return_url: http://google.com?charge_id=675931192
                summary: Activate an application charge
      summary: Shopify This Endpoint Is No Longer Required And Is Deprecated As Of  Api Version 2021-01
      description: https://shopify.dev/docs/admin-api/rest/reference/billing/applicationcharge#activate-2020-10
      parameters:
      - in: path
        name: application_charge_id
        required: true
        schema:
          type: string
        description: application_charge_id
      tags:
      - Required
      responses:
        '200':
          description: ''
      operationId: create_application_charges_param_application_charge_id_activate
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-01/recurring_application_charges/{recurring_application_charge_id}/activate.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  recurring_application_charge:
                    id: 455696195
                    name: Super Mega Plan
                    api_client_id: 755357713
                    price: '15.00'
                    status: accepted
                    return_url: http://yourapp.com
                    billing_on: '2020-12-07'
                    created_at: '2020-12-07T15:53:44-05:00'
                    updated_at: '2020-12-06T19:00:00-05:00'
                    test: null
                    activated_on: null
                    cancelled_on: null
                    trial_days: 0
                    trial_ends_on: null
                    decorated_return_url: http://yourapp.com?charge_id=455696195
                summary: Activate a recurring application charge
      summary: Shopify This Endpoint Is No Longer Required And Is Deprecated As Of  Api Version 2021-01
      description: https://shopify.dev/docs/admin-api/rest/reference/billing/recurringapplicationcharge#activate-2020-01
      parameters:
      - in: path
        name: recurring_application_charge_id
        required: true
        schema:
          type: string
        description: recurring_application_charge_id
      tags:
      - Required
      responses:
        '200':
          description: ''
      operationId: deprecated_202001_create_recurring_application_charges_param_recurring_application_charge_id_activate
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-04/recurring_application_charges/{recurring_application_charge_id}/activate.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  recurring_application_charge:
                    id: 455696195
                    name: Super Mega Plan
                    api_client_id: 755357713
                    price: '15.00'
                    status: accepted
                    return_url: http://yourapp.com
                    billing_on: '2020-12-07'
                    created_at: '2020-12-07T15:53:44-05:00'
                    updated_at: '2020-12-06T19:00:00-05:00'
                    test: null
                    activated_on: null
                    cancelled_on: null
                    trial_days: 0
                    trial_ends_on: null
                    decorated_return_url: http://yourapp.com?charge_id=455696195
                summary: Activate a recurring application charge
      summary: Shopify This Endpoint Is No Longer Required And Is Deprecated As Of  Api Version 2021-01
      description: https://shopify.dev/docs/admin-api/rest/reference/billing/recurringapplicationcharge#activate-2020-04
      parameters:
      - in: path
        name: recurring_application_charge_id
        required: true
        schema:
          type: string
        description: recurring_application_charge_id
      tags:
      - Required
      responses:
        '200':
          description: ''
      operationId: deprecated_202004_create_recurring_application_charges_param_recurring_application_charge_id_activate
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-07/recurring_application_charges/{recurring_application_charge_id}/activate.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  recurring_application_charge:
                    id: 455696195
                    name: Super Mega Plan
                    api_client_id: 755357713
                    price: '15.00'
                    status: accepted
                    return_url: http://yourapp.com
                    billing_on: '2020-12-07'
                    created_at: '2020-12-07T15:53:44-05:00'
                    updated_at: '2020-12-06T19:00:00-05:00'
                    test: null
                    activated_on: null
                    cancelled_on: null
                    trial_days: 0
                    trial_ends_on: null
                    decorated_return_url: http://yourapp.com?charge_id=455696195
                summary: Activate a recurring application charge
      summary: Shopify This Endpoint Is No Longer Required And Is Deprecated As Of  Api Version 2021-01
      description: https://shopify.dev/docs/admin-api/rest/reference/billing/recurringapplicationcharge#activate-2020-07
      parameters:
      - in: path
        name: recurring_application_charge_id
        required: true
        schema:
          type: string
        description: recurring_application_charge_id
      tags:
      - Required
      responses:
        '200':
          description: ''
      operationId: deprecated_202007_create_recurring_application_charges_param_recurring_application_charge_id_activate
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-10/recurring_application_charges/{recurring_application_charge_id}/activate.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  recurring_application_charge:
                    id: 455696195
                    name: Super Mega Plan
                    api_client_id: 755357713
                    price: '15.00'
                    status: accepted
                    return_url: http://yourapp.com
                    billing_on: '2020-12-07'
                    created_at: '2020-12-07T15:53:44-05:00'
                    updated_at: '2020-12-06T19:00:00-05:00'
                    test: null
                    activated_on: null
                    cancelled_on: null
                    trial_days: 0
                    trial_ends_on: null
                    decorated_return_url: http://yourapp.com?charge_id=455696195
                summary: Activate a recurring application charge
      summary: Shopify This Endpoint Is No Longer Required And Is Deprecated As Of  Api Version 2021-01
      description: https://shopify.dev/docs/admin-api/rest/reference/billing/recurringapplicationcharge#activate-2020-10
      parameters:
      - in: path
        name: recurring_application_charge_id
        required: true
        schema:
          type: string
        description: recurring_application_charge_id
      tags:
      - Required
      responses:
        '200':
          description: ''
      operationId: create_recurring_application_charges_param_recurring_application_charge_id_activate
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
components:
  securitySchemes:
    AccessToken:
      type: apiKey
      name: X-Shopify-Access-Token
      in: header
      description: Access token obtained via OAuth
