openapi: 3.1.0
info:
  title: Shopify Admin REST About Sends API
  description: The Shopify Admin REST API lets you build apps and integrations that extend and enhance the Shopify admin. Access products, customers, orders, inventory, fulfillment, and more. Endpoints are organized by resource type and versioned by release date.
  version: 2025-01
  contact:
    name: Shopify
    url: https://shopify.dev/docs/api/admin-rest
    email: api@shopify.com
  license:
    name: Shopify API Terms
    url: https://www.shopify.com/legal/api-terms
  x-date: '2026-03-04'
servers:
- url: https://{store}.myshopify.com/admin/api/2025-01
  description: Shopify Admin REST API
  variables:
    store:
      default: my-store
      description: The Shopify store subdomain
security:
- AccessToken: []
tags:
- name: Sends
paths:
  /admin/api/2020-01/customers/{customer_id}/send_invite.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  customer_invite: {}
                summary: Send the default invite
              example2:
                value:
                  customer_invite:
                    to: new_test_email@shopify.com
                    from: noaccesssteve@jobs.com
                    bcc:
                    - noaccesssteve@jobs.com
                    subject: Welcome to my new shop
                    custom_message: My awesome new store
                summary: Send a customized invite
      summary: Shopify Sends An Account Invite To A Customer
      description: https://shopify.dev/docs/admin-api/rest/reference/customers/customer#send_invite-2020-01
      parameters:
      - in: path
        name: customer_id
        required: true
        schema:
          type: string
        description: customer_id
      tags:
      - Sends
      responses:
        '200':
          description: ''
      operationId: deprecated_202001_create_customers_param_customer_id_send_invite
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-04/customers/{customer_id}/send_invite.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  customer_invite: {}
                summary: Send the default invite
              example2:
                value:
                  customer_invite:
                    to: new_test_email@shopify.com
                    from: noaccesssteve@jobs.com
                    bcc:
                    - noaccesssteve@jobs.com
                    subject: Welcome to my new shop
                    custom_message: My awesome new store
                summary: Send a customized invite
      summary: Shopify Sends An Account Invite To A Customer
      description: https://shopify.dev/docs/admin-api/rest/reference/customers/customer#send_invite-2020-04
      parameters:
      - in: path
        name: customer_id
        required: true
        schema:
          type: string
        description: customer_id
      tags:
      - Sends
      responses:
        '200':
          description: ''
      operationId: deprecated_202004_create_customers_param_customer_id_send_invite
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-07/customers/{customer_id}/send_invite.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  customer_invite: {}
                summary: Send the default invite
              example2:
                value:
                  customer_invite:
                    to: new_test_email@shopify.com
                    from: noaccesssteve@jobs.com
                    bcc:
                    - noaccesssteve@jobs.com
                    subject: Welcome to my new shop
                    custom_message: My awesome new store
                summary: Send a customized invite
      summary: Shopify Sends An Account Invite To A Customer
      description: https://shopify.dev/docs/admin-api/rest/reference/customers/customer#send_invite-2020-07
      parameters:
      - in: path
        name: customer_id
        required: true
        schema:
          type: string
        description: customer_id
      tags:
      - Sends
      responses:
        '200':
          description: ''
      operationId: deprecated_202007_create_customers_param_customer_id_send_invite
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-10/customers/{customer_id}/send_invite.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  customer_invite: {}
                summary: Send the default invite
              example2:
                value:
                  customer_invite:
                    to: new_test_email@shopify.com
                    from: noaccesssteve@jobs.com
                    bcc:
                    - noaccesssteve@jobs.com
                    subject: Welcome to my new shop
                    custom_message: My awesome new store
                summary: Send a customized invite
      summary: Shopify Sends An Account Invite To A Customer
      description: https://shopify.dev/docs/admin-api/rest/reference/customers/customer#send_invite-2020-10
      parameters:
      - in: path
        name: customer_id
        required: true
        schema:
          type: string
        description: customer_id
      tags:
      - Sends
      responses:
        '200':
          description: ''
      operationId: create_customers_param_customer_id_send_invite
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2021-01/customers/{customer_id}/send_invite.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  customer_invite: {}
                summary: Send the default invite
              example2:
                value:
                  customer_invite:
                    to: new_test_email@shopify.com
                    from: noaccesssteve@jobs.com
                    bcc:
                    - noaccesssteve@jobs.com
                    subject: Welcome to my new shop
                    custom_message: My awesome new store
                summary: Send a customized invite
      summary: Shopify Sends An Account Invite To A Customer
      description: https://shopify.dev/docs/admin-api/rest/reference/customers/customer#send_invite-2021-01
      parameters:
      - in: path
        name: customer_id
        required: true
        schema:
          type: string
        description: customer_id
      tags:
      - Sends
      responses:
        '200':
          description: ''
      operationId: deprecated_202101_create_customers_param_customer_id_send_invite
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/unstable/customers/{customer_id}/send_invite.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  customer_invite: {}
                summary: Send the default invite
              example2:
                value:
                  customer_invite:
                    to: new_test_email@shopify.com
                    from: noaccesssteve@jobs.com
                    bcc:
                    - noaccesssteve@jobs.com
                    subject: Welcome to my new shop
                    custom_message: My awesome new store
                summary: Send a customized invite
      summary: Shopify Sends An Account Invite To A Customer
      description: https://shopify.dev/docs/admin-api/rest/reference/customers/customer#send_invite-unstable
      parameters:
      - in: path
        name: customer_id
        required: true
        schema:
          type: string
        description: customer_id
      tags:
      - Sends
      responses:
        '200':
          description: ''
      operationId: deprecated_unstable_create_customers_param_customer_id_send_invite
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-01/fulfillment_orders/{fulfillment_order_id}/cancellation_request.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  cancellation_request:
                    message: The customer changed his mind.
                summary: Sends a cancellation request to the fulfillment service of a fulfillment order and updates the fulfillment order
      summary: Shopify Sends A Cancellation Request To The Fulfillment Service Of A Fulfillment Order
      description: https://shopify.dev/docs/admin-api/rest/reference/shipping-and-fulfillment/cancellationrequest#create-2020-01
      parameters:
      - in: path
        name: fulfillment_order_id
        required: true
        schema:
          type: string
        description: fulfillment_order_id
      - in: query
        name: message
        description: An optional reason for the cancellation request.
        schema: {}
        required: false
      tags:
      - Sends
      responses:
        '200':
          description: ''
      operationId: deprecated_202001_create_fulfillment_orders_param_fulfillment_order_id_cancellation_request
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-04/fulfillment_orders/{fulfillment_order_id}/cancellation_request.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  cancellation_request:
                    message: The customer changed his mind.
                summary: Sends a cancellation request to the fulfillment service of a fulfillment order and updates the fulfillment order
      summary: Shopify Sends A Cancellation Request To The Fulfillment Service Of A Fulfillment Order
      description: https://shopify.dev/docs/admin-api/rest/reference/shipping-and-fulfillment/cancellationrequest#create-2020-04
      parameters:
      - in: path
        name: fulfillment_order_id
        required: true
        schema:
          type: string
        description: fulfillment_order_id
      - in: query
        name: message
        description: An optional reason for the cancellation request.
        schema: {}
        required: false
      tags:
      - Sends
      responses:
        '200':
          description: ''
      operationId: deprecated_202004_create_fulfillment_orders_param_fulfillment_order_id_cancellation_request
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-07/fulfillment_orders/{fulfillment_order_id}/cancellation_request.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  cancellation_request:
                    message: The customer changed his mind.
                summary: Sends a cancellation request to the fulfillment service of a fulfillment order and updates the fulfillment order
      summary: Shopify Sends A Cancellation Request To The Fulfillment Service Of A Fulfillment Order
      description: https://shopify.dev/docs/admin-api/rest/reference/shipping-and-fulfillment/cancellationrequest#create-2020-07
      parameters:
      - in: path
        name: fulfillment_order_id
        required: true
        schema:
          type: string
        description: fulfillment_order_id
      - in: query
        name: message
        description: An optional reason for the cancellation request.
        schema: {}
        required: false
      tags:
      - Sends
      responses:
        '200':
          description: ''
      operationId: deprecated_202007_create_fulfillment_orders_param_fulfillment_order_id_cancellation_request
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-10/fulfillment_orders/{fulfillment_order_id}/cancellation_request.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  cancellation_request:
                    message: The customer changed his mind.
                summary: Sends a cancellation request to the fulfillment service of a fulfillment order and updates the fulfillment order
      summary: Shopify Sends A Cancellation Request To The Fulfillment Service Of A Fulfillment Order
      description: https://shopify.dev/docs/admin-api/rest/reference/shipping-and-fulfillment/cancellationrequest#create-2020-10
      parameters:
      - in: path
        name: fulfillment_order_id
        required: true
        schema:
          type: string
        description: fulfillment_order_id
      - in: query
        name: message
        description: An optional reason for the cancellation request.
        schema: {}
        required: false
      tags:
      - Sends
      responses:
        '200':
          description: ''
      operationId: create_fulfillment_orders_param_fulfillment_order_id_cancellation_request
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2021-01/fulfillment_orders/{fulfillment_order_id}/cancellation_request.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  cancellation_request:
                    message: The customer changed his mind.
                summary: Sends a cancellation request to the fulfillment service of a fulfillment order and updates the fulfillment order
      summary: Shopify Sends A Cancellation Request To The Fulfillment Service Of A Fulfillment Order
      description: https://shopify.dev/docs/admin-api/rest/reference/shipping-and-fulfillment/cancellationrequest#create-2021-01
      parameters:
      - in: path
        name: fulfillment_order_id
        required: true
        schema:
          type: string
        description: fulfillment_order_id
      - in: query
        name: message
        description: An optional reason for the cancellation request.
        schema: {}
        required: false
      tags:
      - Sends
      responses:
        '200':
          description: ''
      operationId: deprecated_202101_create_fulfillment_orders_param_fulfillment_order_id_cancellation_request
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/unstable/fulfillment_orders/{fulfillment_order_id}/cancellation_request.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  cancellation_request:
                    message: The customer changed his mind.
                summary: Sends a cancellation request to the fulfillment service of a fulfillment order and updates the fulfillment order
      summary: Shopify Sends A Cancellation Request To The Fulfillment Service Of A Fulfillment Order
      description: https://shopify.dev/docs/admin-api/rest/reference/shipping-and-fulfillment/cancellationrequest#create-unstable
      parameters:
      - in: path
        name: fulfillment_order_id
        required: true
        schema:
          type: string
        description: fulfillment_order_id
      - in: query
        name: message
        description: An optional reason for the cancellation request.
        schema: {}
        required: false
      tags:
      - Sends
      responses:
        '200':
          description: ''
      operationId: deprecated_unstable_create_fulfillment_orders_param_fulfillment_order_id_cancellation_request
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-01/fulfillment_orders/{fulfillment_order_id}/fulfillment_request.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  fulfillment_request:
                    message: Fulfill this ASAP please.
                    fulfillment_order_line_items:
                    - id: 1025578671
                      quantity: 1
                    - id: 1025578672
                      quantity: 1
                summary: Sends a fulfillment request to the fulfillment service of a fulfillment order for the specified line items
              example2:
                value:
                  fulfillment_request:
                    message: Fulfill this ASAP please.
                summary: Sends a fulfillment request to the fulfillment service for all line items on the fulfillment order if fulfillment_order_line_items is left blank
      summary: Shopify Sends A Fulfillment Request To The Fulfillment Service Of A Fulfillment Order
      description: https://shopify.dev/docs/admin-api/rest/reference/shipping-and-fulfillment/fulfillmentrequest#create-2020-01
      parameters:
      - in: path
        name: fulfillment_order_id
        required: true
        schema:
          type: string
        description: fulfillment_order_id
      - in: query
        name: message
        description: An optional message for the fulfillment request.
        schema: {}
        required: false
      - in: query
        name: fulfillment_order_line_items
        description: The fulfillment order line items to be requested for fulfillment. If left blank, all line items of the fulfillment order are requested for fulfillment.
        schema: {}
        required: false
      tags:
      - Sends
      responses:
        '200':
          description: ''
      operationId: deprecated_202001_create_fulfillment_orders_param_fulfillment_order_id_fulfillment_request
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-04/fulfillment_orders/{fulfillment_order_id}/fulfillment_request.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  fulfillment_request:
                    message: Fulfill this ASAP please.
                    fulfillment_order_line_items:
                    - id: 1025578671
                      quantity: 1
                    - id: 1025578672
                      quantity: 1
                summary: Sends a fulfillment request to the fulfillment service of a fulfillment order for the specified line items
              example2:
                value:
                  fulfillment_request:
                    message: Fulfill this ASAP please.
                summary: Sends a fulfillment request to the fulfillment service for all line items on the fulfillment order if fulfillment_order_line_items is left blank
      summary: Shopify Sends A Fulfillment Request To The Fulfillment Service Of A Fulfillment Order
      description: https://shopify.dev/docs/admin-api/rest/reference/shipping-and-fulfillment/fulfillmentrequest#create-2020-04
      parameters:
      - in: path
        name: fulfillment_order_id
        required: true
        schema:
          type: string
        description: fulfillment_order_id
      - in: query
        name: message
        description: An optional message for the fulfillment request.
        schema: {}
        required: false
      - in: query
        name: fulfillment_order_line_items
        description: The fulfillment order line items to be requested for fulfillment. If left blank, all line items of the fulfillment order are requested for fulfillment.
        schema: {}
        required: false
      tags:
      - Sends
      responses:
        '200':
          description: ''
      operationId: deprecated_202004_create_fulfillment_orders_param_fulfillment_order_id_fulfillment_request
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-07/fulfillment_orders/{fulfillment_order_id}/fulfillment_request.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  fulfillment_request:
                    message: Fulfill this ASAP please.
                    fulfillment_order_line_items:
                    - id: 1025578671
                      quantity: 1
                    - id: 1025578672
                      quantity: 1
                summary: Sends a fulfillment request to the fulfillment service of a fulfillment order for the specified line items
              example2:
                value:
                  fulfillment_request:
                    message: Fulfill this ASAP please.
                summary: Sends a fulfillment request to the fulfillment service for all line items on the fulfillment order if fulfillment_order_line_items is left blank
      summary: Shopify Sends A Fulfillment Request To The Fulfillment Service Of A Fulfillment Order
      description: https://shopify.dev/docs/admin-api/rest/reference/shipping-and-fulfillment/fulfillmentrequest#create-2020-07
      parameters:
      - in: path
        name: fulfillment_order_id
        required: true
        schema:
          type: string
        description: fulfillment_order_id
      - in: query
        name: message
        description: An optional message for the fulfillment request.
        schema: {}
        required: false
      - in: query
        name: fulfillment_order_line_items
        description: The fulfillment order line items to be requested for fulfillment. If left blank, all line items of the fulfillment order are requested for fulfillment.
        schema: {}
        required: false
      tags:
      - Sends
      responses:
        '200':
          description: ''
      operationId: deprecated_202007_create_fulfillment_orders_param_fulfillment_order_id_fulfillment_request
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-10/fulfillment_orders/{fulfillment_order_id}/fulfillment_request.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  fulfillment_request:
                    message: Fulfill this ASAP please.
                    fulfillment_order_line_items:
                    - id: 1025578671
                      quantity: 1
                    - id: 1025578672
                      quantity: 1
                summary: Sends a fulfillment request to the fulfillment service of a fulfillment order for the specified line items
              example2:
                value:
                  fulfillment_request:
                    message: Fulfill this ASAP please.
                summary: Sends a fulfillment request to the fulfillment service for all line items on the fulfillment order if fulfillment_order_line_items is left blank
      summary: Shopify Sends A Fulfillment Request To The Fulfillment Service Of A Fulfillment Order
      description: https://shopify.dev/docs/admin-api/rest/reference/shipping-and-fulfillment/fulfillmentrequest#create-2020-10
      parameters:
      - in: path
        name: fulfillment_order_id
        required: true
        schema:
          type: string
        description: fulfillment_order_id
      - in: query
        name: message
        description: An optional message for the fulfillment request.
        schema: {}
        required: false
      - in: query
        name: fulfillment_order_line_items
        description: The fulfillment order line items to be requested for fulfillment. If left blank, all line items of the fulfillment order are requested for fulfillment.
        schema: {}
        required: false
      tags:
      - Sends
      responses:
        '200':
          description: ''
      operationId: create_fulfillment_orders_param_fulfillment_order_id_fulfillment_request
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2021-01/fulfillment_orders/{fulfillment_order_id}/fulfillment_request.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  fulfillment_request:
                    message: Fulfill this ASAP please.
                    fulfillment_order_line_items:
                    - id: 1025578671
                      quantity: 1
                    - id: 1025578672
                      quantity: 1
                summary: Sends a fulfillment request to the fulfillment service of a fulfillment order for the specified line items
              example2:
                value:
                  fulfillment_request:
                    message: Fulfill this ASAP please.
                summary: Sends a fulfillment request to the fulfillment service for all line items on the fulfillment order if fulfillment_order_line_items is left blank
      summary: Shopify Sends A Fulfillment Request To The Fulfillment Service Of A Fulfillment Order
      description: https://shopify.dev/docs/admin-api/rest/reference/shipping-and-fulfillment/fulfillmentrequest#create-2021-01
      parameters:
      - in: path
        name: fulfillment_order_id
        required: true
        schema:
          type: string
        description: fulfillment_order_id
      - in: query
        name: message
        description: An optional message for the fulfillment request.
        schema: {}
        required: false
      - in: query
        name: fulfillment_order_line_items
        description: The fulfillment order line items to be requested for fulfillment. If left blank, all line items of the fulfillment order are requested for fulfillment.
        schema: {}
        required: false
      tags:
      - Sends
      responses:
        '200':
          description: ''
      operationId: deprecated_202101_create_fulfillment_orders_param_fulfillment_order_id_fulfillment_request
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/unstable/fulfillment_orders/{fulfillment_order_id}/fulfillment_request.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  fulfillment_request:
                    message: Fulfill this ASAP please.
                    fulfillment_order_line_items:
                    - id: 1025578671
                      quantity: 1
                    - id: 1025578672
                      quantity: 1
                summary: Sends a fulfillment request to the fulfillment service of a fulfillment order for the specified line items
              example2:
                value:
                  fulfillment_request:
                    message: Fulfill this ASAP please.
                summary: Sends a fulfillment request to the fulfillment service for all line items on the fulfillment order if fulfillment_order_line_items is left blank
      summary: Shopify Sends A Fulfillment Request To The Fulfillment Service Of A Fulfillment Order
      description: https://shopify.dev/docs/admin-api/rest/reference/shipping-and-fulfillment/fulfillmentrequest#create-unstable
      parameters:
      - in: path
        name: fulfillment_order_id
        required: true
        schema:
          type: string
        description: fulfillment_order_id
      - in: query
        name: message
        description: An optional message for the fulfillment request.
        schema: {}
        required: false
      - in: query
        name: fulfillment_order_line_items
        description: The fulfillment order line items to be requested for fulfillment. If left blank, all line items of the fulfillment order are requested for fulfillment.
        schema: {}
        required: false
      tags:
      - Sends
      responses:
        '200':
          description: ''
      operationId: deprecated_unstable_create_fulfillment_orders_param_fulfillment_order_id_fulfillment_request
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
components:
  securitySchemes:
    AccessToken:
      type: apiKey
      name: X-Shopify-Access-Token
      in: header
      description: Access token obtained via OAuth
